log_paths:
  log_parent_folder: "path/to/parent/folder"

players:
  - name: "placeholder1"
    ip: "10.0.1.105"

  - name: "placeholder2"
    ip: "10.0.1.115"

  - name: "teplaceholder3"
    ip: "10.0.1.106"

  - name: "placeholder4"
    ip: "10.0.1.107"
